
Disease Prediction from Symptoms




# Import Dependencies
import csv
import pandas as pd
import numpy as np
from collections import defaultdict
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
# Read Raw Dataset
df = pd.read_excel('./dataset/raw_data.xlsx')
df.head()
Disease	Count of Disease Occurrence	Symptom
0	UMLS:C0020538_hypertensive disease	3363.0	UMLS:C0008031_pain chest
1	NaN	NaN	UMLS:C0392680_shortness of breath
2	NaN	NaN	UMLS:C0012833_dizziness
3	NaN	NaN	UMLS:C0004093_asthenia
4	NaN	NaN	UMLS:C0085639_fall
# Fill all NaN with the values above
data = df.fillna(method='ffill')
data.head()
Disease	Count of Disease Occurrence	Symptom
0	UMLS:C0020538_hypertensive disease	3363.0	UMLS:C0008031_pain chest
1	UMLS:C0020538_hypertensive disease	3363.0	UMLS:C0392680_shortness of breath
2	UMLS:C0020538_hypertensive disease	3363.0	UMLS:C0012833_dizziness
3	UMLS:C0020538_hypertensive disease	3363.0	UMLS:C0004093_asthenia
4	UMLS:C0020538_hypertensive disease	3363.0	UMLS:C0085639_fall
# Process Disease and Symptom Names
def process_data(data):
    data_list = []
    data_name = data.replace('^','_').split('_')
    n = 1
    for names in data_name:
        if (n % 2 == 0):
            data_list.append(names)
        n += 1
    return data_list
# Data Cleanup
disease_list = []
disease_symptom_dict = defaultdict(list)
disease_symptom_count = {}
count = 0

for idx, row in data.iterrows():
    
    # Get the Disease Names
    if (row['Disease'] !="\xc2\xa0") and (row['Disease'] != ""):
        disease = row['Disease']
        disease_list = process_data(data=disease)
        count = row['Count of Disease Occurrence']

    # Get the Symptoms Corresponding to Diseases
    if (row['Symptom'] !="\xc2\xa0") and (row['Symptom'] != ""):
        symptom = row['Symptom']
        symptom_list = process_data(data=symptom)
        for d in disease_list:
            for s in symptom_list:
                disease_symptom_dict[d].append(s)
            disease_symptom_count[d] = count
# See that the data is Processed Correctly
disease_symptom_dict
defaultdict(list,
            {'hypertensive disease': ['pain chest',
              'shortness of breath',
              'dizziness',
              'asthenia',
              'fall',
              'syncope',
              'vertigo',
              'sweat',
              'sweating increased',
              'palpitation',
              'nausea',
              'angina pectoris',
              'pressure chest'],
             'diabetes': ['polyuria',
              'polydypsia',
              'shortness of breath',
              'pain chest',
              'asthenia',
              'nausea',
              'orthopnea',
              'rale',
              'sweat',
              'sweating increased',
              'unresponsiveness',
              'mental status changes',
              'vertigo',
              'vomiting',
              'labored breathing'],
             'depression mental': ['feeling suicidal',
              'suicidal',
              'hallucinations auditory',
              'feeling hopeless',
              'weepiness',
              'sleeplessness',
              'motor retardation',
              'irritable mood',
              'blackout',
              'mood depressed',
              'hallucinations visual',
              'worry',
              'agitation',
              'tremor',
              'intoxication',
              'verbal auditory hallucinations',
              'energy increased',
              'difficulty',
              'nightmare',
              'unable to concentrate',
              'homelessness'],
             'depressive disorder': ['feeling suicidal',
              'suicidal',
              'hallucinations auditory',
              'feeling hopeless',
              'weepiness',
              'sleeplessness',
              'motor retardation',
              'irritable mood',
              'blackout',
              'mood depressed',
              'hallucinations visual',
              'worry',
              'agitation',
              'tremor',
              'intoxication',
              'verbal auditory hallucinations',
              'energy increased',
              'difficulty',
              'nightmare',
              'unable to concentrate',
              'homelessness'],
             'coronary arteriosclerosis': ['pain chest',
              'angina pectoris',
              'shortness of breath',
              'hypokinesia',
              'sweat',
              'sweating increased',
              'pressure chest',
              'dyspnea on exertion',
              'orthopnea',
              'chest tightness'],
             'coronary heart disease': ['pain chest',
              'angina pectoris',
              'shortness of breath',
              'hypokinesia',
              'sweat',
              'sweating increased',
              'pressure chest',
              'dyspnea on exertion',
              'orthopnea',
              'chest tightness'],
             'pneumonia': ['cough',
              'fever',
              'decreased translucency',
              'shortness of breath',
              'rale',
              'productive cough',
              'pleuritic pain',
              'yellow sputum',
              'breath sounds decreased',
              'chill',
              'rhonchus',
              'green sputum',
              'non-productive cough',
              'wheezing',
              'haemoptysis',
              'distress respiratory',
              'tachypnea',
              'malaise',
              'night sweat'],
             'failure heart congestive': ['shortness of breath',
              'orthopnea',
              'jugular venous distention',
              'rale',
              'dyspnea',
              'cough',
              'wheezing'],
             'accident\xa0cerebrovascular': ['dysarthria',
              'asthenia',
              'speech slurred',
              'facial paresis',
              'hemiplegia',
              'unresponsiveness',
              'seizure',
              'numbness'],
             'asthma': ['wheezing',
              'cough',
              'shortness of breath',
              'chest tightness',
              'non-productive cough',
              'pleuritic pain',
              'productive cough',
              'symptom aggravating factors',
              'distress respiratory'],
             'myocardial infarction': ['pain chest',
              'st segment elevation',
              'sweat',
              'sweating increased',
              'shortness of breath',
              'st segment depression',
              'hypokinesia',
              'angina pectoris',
              'pressure chest',
              't wave inverted',
              'orthopnea',
              'rale',
              'chest tightness',
              'presence of q wave',
              'palpitation',
              'dyspnea',
              'chest discomfort',
              'bradycardia',
              'syncope'],
             'hypercholesterolemia': ['pain',
              'pain chest',
              'sweat',
              'sweating increased',
              'nonsmoker',
              'pressure chest',
              'syncope',
              'numbness',
              'chest discomfort',
              'shortness of breath',
              'st segment depression',
              'worry',
              't wave inverted',
              'bradycardia',
              'dyspnea'],
             'infection': ['fever',
              'erythema',
              'decreased translucency',
              'hepatosplenomegaly',
              'chill',
              'pruritus',
              'diarrhea',
              'abscess bacterial',
              'swelling',
              'pain',
              'apyrexial',
              'cough'],
             'infection urinary tract': ['fever',
              'dysuria',
              'hematuria',
              'renal angle tenderness',
              'lethargy',
              'asthenia',
              'hyponatremia',
              'hemodynamically stable',
              'distress respiratory',
              'difficulty passing urine',
              'mental status changes',
              'consciousness clear'],
             'anemia': ['chill',
              'guaiac positive',
              'monoclonal',
              'ecchymosis',
              'tumor cell invasion',
              'haemorrhage',
              'pallor',
              'asthenia',
              'fatigue',
              'heme positive',
              'pain back',
              'orthostasis',
              'hyponatremia',
              'dizziness',
              'shortness of breath',
              'pain',
              'rhonchus',
              'arthralgia',
              'swelling',
              'transaminitis'],
             'chronic obstructive airway disease': ['shortness of breath',
              'wheezing',
              'cough',
              'dyspnea',
              'distress respiratory',
              'sputum purulent',
              'hypoxemia',
              'hypercapnia',
              'patient non compliance',
              'chest tightness'],
             'dementia': ['fever',
              'fall',
              'unresponsiveness',
              'lethargy',
              'agitation',
              'ecchymosis',
              'syncope',
              'rale',
              'unconscious state',
              'cough',
              'bedridden',
              'bedridden',
              'pain',
              'facial paresis',
              'abdominal tenderness',
              'rhonchus',
              'unsteady gait',
              'hallucinations auditory'],
             'insufficiency renal': ['shortness of breath',
              'hyperkalemia',
              'orthopnea',
              'rale',
              'urgency of\xa0micturition',
              'ascites',
              'guaiac positive',
              'asthenia',
              'apyrexial',
              'mental status changes',
              'dyspnea',
              'difficulty',
              'diarrhea',
              'hypotension',
              'breath sounds decreased',
              'swelling',
              'hypokinesia'],
             'confusion': ['seizure',
              'enuresis',
              'lethargy',
              'speech slurred',
              'fall',
              'consciousness clear',
              'mental status changes',
              'asterixis',
              'unconscious state',
              'agitation',
              'muscle twitch',
              'asthenia',
              'sleepy',
              'dizziness',
              'headache',
              'dysarthria',
              'lightheadedness',
              'tremor',
              'hyponatremia',
              'unresponsiveness'],
             'degenerative\xa0polyarthritis': ['pain',
              'food intolerance',
              'numbness of hand',
              'general discomfort',
              'drowsiness',
              'asthenia',
              'nonsmoker',
              'non-productive cough',
              'polydypsia',
              'stiffness',
              'unsteady gait'],
             'hypothyroidism': ['shortness of breath',
              'prostatism',
              'drowsiness',
              'sleepy',
              'hyponatremia',
              'fall',
              'unsteady gait',
              'polyuria',
              'hypotension',
              'difficulty',
              'syncope',
              'nightmare',
              'speech slurred',
              'weight gain',
              'asthenia',
              'fatigue',
              'tired',
              'agitation',
              'mental status changes',
              'motor retardation',
              'vomiting',
              'numbness',
              'mass of body structure'],
             'anxiety state': ['worry',
              'feeling suicidal',
              'suicidal',
              'sleeplessness',
              'feeling hopeless',
              'irritable mood',
              'tremor',
              'blackout',
              'weepiness',
              'has religious belief',
              'nervousness',
              'hallucinations visual',
              'formication',
              'difficulty',
              'pain chest',
              'patient non compliance',
              'agitation',
              'palpitation',
              'hallucinations auditory',
              'mood depressed',
              'hot flush',
              'pain',
              'consciousness clear',
              'nightmare'],
             'malignant neoplasms': ['pain',
              'mass of body structure',
              'lesion',
              'cushingoid facies',
              'cushingoid\xa0habitus',
              'emphysematous change',
              'decreased body weight',
              'ascites',
              'hoarseness',
              'thicken',
              'hematuria'],
             'primary malignant neoplasm': ['pain',
              'mass of body structure',
              'lesion',
              'cushingoid facies',
              'cushingoid\xa0habitus',
              'emphysematous change',
              'decreased body weight',
              'ascites',
              'hoarseness',
              'thicken',
              'hematuria'],
             'acquired\xa0immuno-deficiency syndrome': ['fever',
              'night sweat',
              'spontaneous rupture of membranes',
              'cough',
              '',
              'decreased body weight',
              'chill',
              'diarrhea',
              'pleuritic pain',
              'patient non compliance',
              'tachypnea',
              'productive cough',
              'muscle hypotonia',
              'hypotonic',
              'feeling suicidal'],
             'HIV': ['fever',
              'night sweat',
              'spontaneous rupture of membranes',
              'cough',
              '',
              'decreased body weight',
              'chill',
              'diarrhea',
              'pleuritic pain',
              'patient non compliance',
              'tachypnea',
              'productive cough',
              'muscle hypotonia',
              'hypotonic',
              'feeling suicidal'],
             'hiv infections': ['fever',
              'night sweat',
              'spontaneous rupture of membranes',
              'cough',
              '',
              'decreased body weight',
              'chill',
              'diarrhea',
              'pleuritic pain',
              'patient non compliance',
              'tachypnea',
              'productive cough',
              'muscle hypotonia',
              'hypotonic',
              'feeling suicidal'],
             'cellulitis': ['erythema',
              'pain',
              'swelling',
              'redness',
              'fever',
              'abscess bacterial',
              'patient non compliance',
              'hypesthesia',
              'hyperacusis',
              'pruritus',
              'pain chest',
              'scratch marks',
              'chill',
              'sore to touch'],
             'gastroesophageal reflux disease': ['pain',
              'pain chest',
              'burning sensation',
              'hyponatremia',
              'satiety early',
              'throbbing sensation quality',
              'chest tightness',
              'sensory discomfort',
              'presence of q wave',
              'nausea',
              'general discomfort',
              'constipation',
              'palpitation',
              'pain abdominal',
              'heartburn',
              'sweat',
              'sweating increased',
              'asthenia'],
             'septicemia': ['fever',
              'distress respiratory',
              'hypotension',
              'tachypnea',
              'chill',
              'lethargy',
              'bradycardia',
              'breech presentation',
              'cyanosis',
              'spontaneous rupture of membranes',
              'haemorrhage',
              'unresponsiveness',
              'rale',
              'apyrexial'],
             'systemic infection': ['fever',
              'distress respiratory',
              'hypotension',
              'tachypnea',
              'chill',
              'lethargy',
              'bradycardia',
              'breech presentation',
              'cyanosis',
              'spontaneous rupture of membranes',
              'haemorrhage',
              'unresponsiveness',
              'rale',
              'apyrexial'],
             'sepsis (invertebrate)': ['fever',
              'distress respiratory',
              'hypotension',
              'tachypnea',
              'chill',
              'lethargy',
              'bradycardia',
              'breech presentation',
              'cyanosis',
              'spontaneous rupture of membranes',
              'haemorrhage',
              'unresponsiveness',
              'rale',
              'apyrexial'],
             'deep vein thrombosis': ['swelling',
              'pain',
              'ecchymosis',
              'shortness of breath',
              'pain in lower limb',
              'cardiomegaly',
              'rale',
              'erythema',
              'hypotension',
              'clonus',
              'non-productive cough',
              'redness'],
             'dehydration': ['fever',
              'diarrhea',
              'vomiting',
              'hypotension',
              'nausea',
              'lightheadedness',
              'unwell',
              'mental status changes',
              'anorexia',
              'asthenia',
              'sensory discomfort',
              'syncope',
              'lethargy',
              'dizziness',
              'syncope',
              'blackout',
              'history of - blackout'],
             'neoplasm': ['mass of body structure',
              'lesion',
              'pain chest',
              'hematuria',
              'tumor cell invasion',
              'pain',
              'anosmia',
              'thicken',
              'metastatic lesion',
              'food intolerance',
              'decreased body weight',
              'night sweat',
              'hemianopsia homonymous',
              'satiety early',
              'pain abdominal',
              'headache'],
             'embolism pulmonary': ['shortness of breath',
              'hypoxemia',
              'tachypnea',
              'hematocrit decreased',
              'pain chest',
              'dyspnea',
              'pleuritic pain',
              'neck stiffness',
              'yellow sputum',
              'productive cough',
              'cicatrisation',
              'unresponsiveness',
              'distress respiratory',
              'wheezing',
              'apyrexial',
              'non-productive cough'],
             'epilepsy': ['seizure',
              'hypometabolism',
              'aura',
              'muscle twitch',
              'drowsiness',
              'tremor',
              'unresponsiveness',
              'hemiplegia',
              'myoclonus',
              'gurgle',
              'sleepy',
              'lethargy',
              'wheelchair bound'],
             'cardiomyopathy': ['shortness of breath',
              'orthopnea',
              'hypokinesia',
              'jugular venous distention',
              'palpitation',
              'pain chest',
              'syncope',
              'yellow sputum',
              'rale',
              'dyspnea',
              'dyspnea on exertion',
              'left\xa0atrial\xa0hypertrophy',
              'fatigue',
              'weight gain',
              'patient non compliance'],
             'chronic kidney failure': ['vomiting',
              'orthopnea',
              'hyperkalemia',
              'oliguria',
              'jugular venous distention',
              'nausea',
              'shortness of breath',
              'mental status changes',
              'diarrhea',
              'asthenia',
              'chest tightness',
              'malaise',
              'chill',
              'rale',
              'fever',
              'pleuritic pain',
              'apyrexial',
              'guaiac positive',
              'swelling',
              'catatonia',
              'unresponsiveness',
              'yellow sputum'],
             'carcinoma': ['mass of body structure',
              'pain',
              'lesion',
              'tumor cell invasion',
              'thicken',
              'decreased body weight',
              'hoarseness',
              'general discomfort',
              'metastatic lesion',
              'non-productive cough',
              'constipation',
              'unhappy',
              'paresthesia',
              'gravida 0',
              'diarrhea',
              'sore to touch',
              'heartburn',
              'nausea',
              'lung nodule'],
             'hepatitis C': ['ascites',
              'distended abdomen',
              'feeling suicidal',
              'cough',
              'ache',
              'macerated skin',
              'heavy feeling',
              'hallucinations auditory',
              'chill',
              'asterixis',
              'patient non compliance'],
             'peripheral vascular disease': ['shortness of breath',
              'rest pain',
              'angina pectoris',
              'unresponsiveness',
              'hyperkalemia',
              'sinus rhythm',
              'labored breathing',
              'dyspnea',
              'sore to touch',
              'anorexia',
              'sleepy'],
             'psychotic disorder': ['suicidal',
              'hallucinations auditory',
              'feeling suicidal',
              'hallucinations visual',
              'motor retardation',
              'blackout',
              'verbal auditory hallucinations',
              'feeling hopeless',
              'irritable mood',
              'agitation',
              'tremor',
              'catatonia',
              'weepiness',
              'homelessness',
              'sleeplessness',
              'withdraw',
              'energy increased',
              'intoxication',
              'worry',
              'behavior hyperactive',
              'patient non compliance',
              'mood depressed',
              'terrify',
              'nightmare',
              'consciousness clear'],
             'hyperlipidemia': ['pain chest',
              'angina pectoris',
              'palpitation',
              'presence of q wave',
              'photopsia',
              'sweat',
              'sweating increased',
              'chest discomfort',
              'shortness of breath',
              'giddy mood',
              'hypokinesia',
              'hemiplegia',
              'dizziness'],
             'bipolar disorder': ['feeling suicidal',
              'energy increased',
              'suicidal',
              'irritable mood',
              'agitation',
              'has religious belief',
              'disturbed family',
              'hallucinations auditory',
              'verbal auditory hallucinations',
              'weepiness',
              'behavior hyperactive',
              'catatonia',
              'feeling hopeless',
              'worry',
              'sleeplessness',
              'hypersomnia',
              'difficulty',
              'hallucinations visual',
              'hyperhidrosis disorder',
              'mydriasis',
              'extrapyramidal sign',
              'loose associations',
              'intoxication',
              'motor retardation',
              'homelessness',
              'blackout',
              'tremor',
              'exhaustion'],
             'obesity': ['pain',
              'catatonia',
              'snore',
              'pain chest',
              'r wave feature',
              'has religious belief',
              'shortness of breath',
              'fatigue',
              'tired',
              'overweight',
              'systolic murmur',
              'mood depressed',
              'ecchymosis'],
             'ischemia': ['drowsiness',
              'sleepy',
              'pain chest',
              'angina pectoris',
              'pressure chest',
              'chest discomfort',
              'shortness of breath',
              'dyspnea',
              'sinus rhythm',
              'bradycardia',
              'sweat',
              'sweating increased',
              'rale',
              'asymptomatic',
              'anorexia'],
             'cirrhosis': ['ascites',
              'fall',
              'splenomegaly',
              'pruritus',
              'pain abdominal',
              'tumor cell invasion',
              'distended abdomen',
              'lesion',
              'hemodynamically stable',
              'guaiac positive',
              'sore to touch',
              'bleeding of vagina'],
             'exanthema': ['fever',
              'pruritus',
              'macule',
              'lesion',
              'redness',
              'headache',
              'apyrexial',
              'arthralgia',
              'swelling',
              'erythema',
              'photophobia',
              'chill',
              'scratch marks',
              'pain',
              'painful swallowing'],
             'benign prostatic hypertrophy': ['mental status changes',
              'cachexia',
              'blackout',
              'orthostasis',
              'orthopnea',
              'night sweat',
              'distress respiratory',
              'anorexia',
              'dysarthria'],
             'kidney failure acute': ['hyperkalemia',
              'hypotension',
              'hypocalcemia result',
              'oliguria',
              'hemodynamically stable',
              'asthenia',
              'hypothermia, natural',
              'diarrhea',
              'haemorrhage',
              'unresponsiveness'],
             'mitral valve insufficiency': ['shortness of breath',
              'dyspnea on exertion',
              'asymptomatic',
              'hypokinesia',
              'dyspnea',
              'syncope',
              'thicken',
              'left\xa0atrial\xa0hypertrophy',
              'palpitation',
              'fatigue',
              'vomiting',
              'pain',
              'cardiomegaly',
              'chest discomfort'],
             'arthritis': ['pain',
              'hemodynamically stable',
              'sleeplessness',
              'asthenia',
              'syncope',
              'swelling',
              'atypia',
              'general unsteadiness',
              'shortness of breath',
              'distended abdomen'],
             'bronchitis': ['cough',
              'wheezing',
              'shortness of breath',
              'chest tightness',
              'fever',
              'throat sore',
              'productive cough',
              'hepatosplenomegaly',
              'night sweat',
              'haemoptysis',
              'labored breathing',
              'snuffle',
              'hacking cough',
              'dyspnea',
              'chill',
              'stridor',
              'decreased body weight'],
             'hemiparesis': ['dysarthria',
              'paresis',
              'asthenia',
              'aphagia',
              'seizure',
              'speech slurred',
              'focal seizures',
              'hemiplegia',
              'abnormal sensation',
              'unresponsiveness',
              'stupor',
              'drowsiness',
              'sleepy',
              'fremitus',
              "Stahli's line",
              'stinging sensation',
              'paralyse',
              'clonus',
              'facial paresis'],
             'osteoporosis': ['prostatism',
              'fall',
              'hirsutism',
              'sniffle',
              'distended abdomen',
              'vertigo',
              'numbness of hand',
              'bradykinesia',
              'pain',
              'syncope',
              'out of breath',
              'apyrexial',
              'urge incontinence',
              'lightheadedness'],
             'transient ischemic attack': ['speech slurred',
              'dysarthria',
              'facial paresis',
              'asthenia',
              'neck stiffness',
              'vertigo',
              'numbness',
              'lightheadedness',
              'extrapyramidal sign',
              "Stahli's line",
              'vision blurred',
              'headache',
              'room spinning',
              'syncope',
              'difficulty',
              'rambling speech',
              'clumsiness'],
             'adenocarcinoma': ['mass of body structure',
              'lesion',
              'decreased body weight',
              'constipation',
              'fremitus',
              'decreased stool caliber',
              'satiety early',
              'hematochezia',
              'egophony',
              'pain',
              'cicatrisation',
              'scar tissue',
              'pain abdominal'],
             'paranoia': ['hallucinations auditory',
              'hallucinations visual',
              'agitation',
              'irritable mood',
              'verbal auditory hallucinations',
              'feeling suicidal',
              'suicidal',
              'terrify',
              'neologism',
              'homelessness',
              'energy increased',
              'mood depressed',
              'decompensation',
              'cicatrisation',
              'scar tissue',
              'blackout',
              'loose associations'],
             'pancreatitis': ['vomiting',
              'pain abdominal',
              'nausea',
              'pain',
              'diarrhea',
              'stool color yellow',
              'rigor - temperature-associated observation',
              'apyrexial',
              'sore to touch'],
             'incontinence': ['paraparesis',
              'seizure',
              'asthenia',
              'urge incontinence',
              'unconscious state',
              'aura',
              'moody',
              'fear of falling',
              'tremor',
              'spasm',
              'unhappy',
              'syncope',
              'fall',
              'stiffness',
              'unresponsiveness'],
             'paroxysmal\xa0dyspnea': ['orthopnea',
              'shortness of breath',
              'dyspnea on exertion',
              'jugular venous distention',
              'rale',
              'pain chest',
              'palpitation',
              'sweat',
              'sweating increased',
              'weight gain',
              'cough',
              'dyspnea'],
             'hernia': ['pain abdominal',
              'pain',
              'hyperventilation',
              'excruciating pain',
              'gag',
              'nausea',
              'posturing',
              'hemiplegia',
              'sore to touch',
              'haemorrhage',
              'apyrexial',
              'food intolerance',
              'pulse absent',
              'asthenia',
              'mass of body structure',
              'thicken'],
             'malignant neoplasm of prostate': ['hematuria',
              'dysesthesia',
              'asthenia',
              'polymyalgia',
              'passed stones',
              'pleuritic pain',
              'guaiac positive',
              'rale',
              'breath sounds decreased',
              'urge incontinence',
              'dysuria',
              'diarrhea',
              'vertigo',
              'qt interval prolonged',
              'ataxia',
              'paresis',
              'hemianopsia homonymous',
              'tumor cell invasion',
              'hemodynamically stable',
              'mass of body structure',
              'rhonchus',
              'orthostasis',
              'decreased body weight'],
             'carcinoma prostate': ['hematuria',
              'dysesthesia',
              'asthenia',
              'polymyalgia',
              'passed stones',
              'pleuritic pain',
              'guaiac positive',
              'rale',
              'breath sounds decreased',
              'urge incontinence',
              'dysuria',
              'diarrhea',
              'vertigo',
              'qt interval prolonged',
              'ataxia',
              'paresis',
              'hemianopsia homonymous',
              'tumor cell invasion',
              'hemodynamically stable',
              'mass of body structure',
              'rhonchus',
              'orthostasis',
              'decreased body weight'],
             'edema pulmonary': ['urgency of\xa0micturition',
              'shortness of breath',
              'rale',
              'tachypnea',
              'orthopnea',
              "Heberden's node",
              'jugular venous distention',
              'dyspnea',
              'sweat',
              'sweating increased',
              'patient non compliance',
              'chest discomfort',
              'hyperkalemia',
              'sinus rhythm',
              'pain chest',
              'hypotension',
              'wheezing'],
             'lymphatic diseases': ['pain',
              'mass of body structure',
              'night sweat',
              'splenomegaly',
              'lesion',
              'chill',
              'decreased body weight',
              'swelling',
              'fever',
              'hyperacusis',
              'fremitus',
              'non-productive cough',
              'egophony',
              'redness',
              'hepatomegaly',
              'fatigue'],
             'stenosis aortic valve': ['dyspnea on exertion',
              'syncope',
              'chest discomfort',
              'systolic murmur',
              'sciatica',
              'angina pectoris',
              'pain chest',
              'frothy sputum',
              'bradycardia',
              'shortness of breath',
              'pain'],
             'malignant neoplasm of breast': ['mass in breast',
              'mass of body structure',
              'paresthesia',
              'retropulsion',
              'erythema',
              'difficulty',
              'lesion',
              'estrogen use',
              'burning sensation',
              'dyspnea',
              'swelling',
              'formication'],
             'carcinoma breast': ['mass in breast',
              'mass of body structure',
              'paresthesia',
              'retropulsion',
              'erythema',
              'difficulty',
              'lesion',
              'estrogen use',
              'burning sensation',
              'dyspnea',
              'swelling',
              'formication'],
             'schizophrenia': ['hallucinations auditory',
              'hypersomnolence',
              'irritable mood',
              'verbal auditory hallucinations',
              'patient non compliance',
              'agitation',
              'suicidal',
              'worry',
              'hallucinations visual',
              'underweight',
              'underweight',
              'homelessness'],
             'diverticulitis': ['pain abdominal',
              'abscess bacterial',
              'dullness',
              'red blotches',
              'diarrhea',
              'sore to touch',
              'dysuria',
              'pain',
              'vomiting',
              'sinus rhythm',
              'colic abdominal',
              'apyrexial',
              'abdominal tenderness',
              'fever',
              'unsteady gait',
              'thicken',
              'urgency of\xa0micturition',
              'anorexia',
              'monoclonal',
              'constipation'],
             'overload fluid': ['rale',
              'jugular venous distention',
              'hyperkalemia',
              'orthopnea',
              'shortness of breath',
              'drowsiness',
              'sleepy',
              'weight gain',
              'hypokalemia',
              'hypotension',
              'swelling',
              'distended abdomen'],
             'ulcer peptic': ['pain abdominal',
              'paraparesis',
              'nausea',
              'vomiting',
              'polymyalgia',
              'out of breath',
              'pain chest',
              'hemiplegia',
              'gurgle',
              'hunger',
              'apyrexial',
              'nervousness'],
             'osteomyelitis': ['pain',
              'redness',
              'prostate tender',
              'fever',
              'difficulty passing urine',
              'sore to touch',
              'swelling',
              'apyrexial',
              'erythema',
              'abscess bacterial',
              'pain foot',
              'urinary hesitation'],
             'gastritis': ['heme positive',
              'pain abdominal',
              'vomiting',
              'disequilibrium',
              'nausea',
              'intoxication',
              'haemorrhage',
              'guaiac positive',
              'pain',
              'decreased body weight',
              'sore to touch',
              'dizziness'],
             'bacteremia': ['fever',
              'chill',
              'flushing',
              'unresponsiveness',
              'indifferent mood',
              'urinoma',
              'vomiting',
              'distended abdomen',
              'hypoalbuminemia',
              'pustule',
              'prostatism',
              'diarrhea',
              'abdominal tenderness',
              'pleuritic pain',
              'decreased translucency',
              'pallor'],
             'failure kidney': ['orthopnea',
              'oliguria',
              'slowing of urinary stream',
              'extreme exhaustion',
              'unresponsiveness',
              'hypotension',
              'enuresis',
              'shortness of breath',
              'haemorrhage',
              'prostatism',
              'no status change',
              'bedridden',
              'bedridden',
              'fatigue'],
             'sickle cell anemia': ['breakthrough pain',
              'pain back',
              'pain',
              'shortness of breath',
              'snuffle',
              'pain chest',
              'pain abdominal',
              'hepatosplenomegaly',
              'green sputum',
              'apyrexial',
              'headache'],
             'failure heart': ['orthopnea',
              'fatigue',
              'dyspnea on exertion',
              'dyspnea',
              'shortness of breath',
              'pansystolic murmur',
              'jugular venous distention',
              'systolic ejection murmur',
              'hypotension',
              'angina pectoris',
              'hypokinesia'],
             'upper respiratory infection': ['cough',
              'throat sore',
              'wheezing',
              'shortness of breath',
              'labored breathing',
              'fever',
              'stuffy nose',
              'non-productive cough',
              'snuffle',
              'indifferent mood',
              'egophony',
              'barking cough',
              'polymyalgia',
              'pleuritic pain',
              'night sweat',
              'dyspnea',
              'productive cough',
              'decreased translucency',
              'rhonchus',
              'rapid shallow breathing',
              'apyrexial',
              'noisy respiration',
              'nasal discharge present',
              'emphysematous change',
              'frail',
              'cystic lesion',
              'symptom aggravating factors',
              'hemodynamically stable'],
             'hepatitis': ['ascites',
              'spontaneous rupture of membranes',
              'tachypnea',
              'pain abdominal',
              'pruritus',
              'anorexia',
              'transaminitis',
              'projectile vomiting',
              'chill',
              'distress respiratory',
              'fever',
              'vomiting'],
             'hypertension pulmonary': ['shortness of breath',
              "Stahli's line",
              'heavy legs',
              'breath sounds decreased',
              'neck stiffness',
              'dyspnea on exertion',
              'cyanosis',
              'hypotension',
              'left\xa0atrial\xa0hypertrophy'],
             'deglutition disorder': ['paresthesia',
              'titubation',
              'dysarthria',
              'painful swallowing',
              'hoarseness',
              'stridor',
              'spasm',
              'asthenia',
              'dysdiadochokinesia',
              'ataxia',
              'achalasia',
              'decreased body weight',
              'stiffness',
              'lesion',
              'side pain'],
             'gout': ['hot flush',
              'pain',
              'redness',
              'swelling',
              'erythema',
              'emphysematous change',
              'sore to touch',
              'hypokinesia',
              'ascites',
              'patient non compliance'],
             'thrombocytopaenia': ['ecchymosis',
              'monocytosis',
              'posterior\xa0rhinorrhea',
              'haemorrhage',
              'tachypnea',
              'fever',
              'pruritus',
              'hypotension',
              'fatigue'],
             'hypoglycemia': ['unresponsiveness',
              'hypothermia, natural',
              'incoherent',
              'qt interval prolonged',
              'lameness',
              'claudication',
              'unconscious state',
              'clammy skin',
              'polyuria',
              'distress respiratory',
              'hypotension'],
             'pneumonia aspiration': ['mediastinal shift',
              'fever',
              'clonus',
              'mental status changes',
              'decreased translucency',
              'unresponsiveness',
              'extreme exhaustion',
              'stupor',
              'seizure',
              'transaminitis',
              'hemiplegia',
              'cough',
              'gurgle',
              'pain',
              'diarrhea',
              'pain abdominal'],
             'colitis': ['fever',
              'thicken',
              'green sputum',
              'vomiting',
              'nausea and vomiting',
              'awakening early',
              'pain',
              'nausea',
              'chill',
              'tenesmus',
              'urge incontinence',
              'pain abdominal',
              'hemodynamically stable'],
             'diverticulosis': ['fecaluria',
              'constipation',
              'abscess bacterial',
              'heme positive',
              'lightheadedness',
              'diarrhea',
              'haemorrhage',
              'pain',
              'projectile vomiting',
              'pneumatouria',
              'cystic lesion',
              'anorexia',
              'nausea',
              'feeling suicidal',
              'feeling hopeless'],
             'suicide attempt': ['hallucinations auditory',
              'sleeplessness',
              'suicidal',
              'motor retardation',
              'weepiness',
              'unable to concentrate',
              'todd paralysis',
              'worry',
              'fatigue',
              'tremor',
              'alcoholic withdrawal symptoms',
              'agitation',
              'unresponsiveness',
              'blackout',
              'withdraw',
              'difficulty',
              'irritable mood',
              'sensory discomfort',
              'drowsiness',
              'formication',
              'unconscious state',
              'fever',
              'cough'],
             'Pneumocystis\xa0carinii\xa0pneumonia': ['yellow sputum',
              'cachexia',
              'chill',
              'decreased body weight',
              'productive cough',
              'myalgia',
              'diarrhea',
              'neck stiffness',
              'hacking cough',
              'dyspareunia',
              'hypokalemia',
              'dyspnea on exertion',
              'poor dentition',
              'transaminitis',
              'non-productive cough',
              'headache',
              'floppy',
              'spontaneous rupture of membranes'],
             'hepatitis B': ['inappropriate affect',
              'tachypnea',
              'yellow sputum',
              'projectile vomiting',
              'poor feeding',
              'pain abdominal',
              'abdominal tenderness',
              'wheelchair bound',
              'moan'],
             'parkinson disease': ['achalasia',
              'fall',
              'stiffness',
              'withdraw',
              'agitation',
              'hemiplegia',
              'difficulty',
              'unresponsiveness',
              'syncope',
              'facial paresis',
              'orthostasis',
              'worry',
              'drowsiness',
              'sleepy',
              'hematuria',
              'tremor',
              'night sweat',
              'mass of body structure'],
             'lymphoma': ['lesion',
              'fever',
              'welt',
              'transaminitis',
              'decreased body weight',
              'ataxia',
              'tinnitus',
              'hydropneumothorax',
              'superimposition',
              'haemoptysis',
              'fatigue',
              'tired',
              'polydypsia',
              'difficulty passing urine'],
             'hyperglycemia': ['sore to touch',
              'pruritus',
              'feeling strange',
              'pustule',
              'cushingoid facies',
              'cushingoid\xa0habitus',
              'decreased body weight',
              'mood depressed',
              'estrogen use',
              'wheezing',
              'ascites',
              'seizure'],
             'encephalopathy': ['uncoordination',
              'asterixis',
              'haemorrhage',
              'drowsiness',
              'sleepy',
              'absences finding',
              'posturing',
              'aura',
              'tonic seizures',
              'debilitation',
              'consciousness clear',
              'unresponsiveness',
              'thicken',
              'hypokinesia'],
             'tricuspid valve insufficiency': ['shortness of breath',
              'pain',
              'vomiting',
              'nausea',
              'bradycardia',
              'pain abdominal',
              'fever',
              'cicatrisation',
              'mediastinal shift',
              'impaired cognition'],
             "Alzheimer's disease": ['drool',
              'agitation',
              'nightmare',
              'rhonchus',
              'consciousness clear',
              'pin-point pupils',
              'bedridden',
              'bedridden',
              'frail',
              'tremor resting',
              'hyperkalemia',
              'facial paresis',
              'groggy',
              'muscle twitch',
              'wheelchair bound',
              'tremor',
              'cough',
              'fever'],
             'candidiasis': ['diarrhea',
              'throat sore',
              'decreased body weight',
              'chill',
              'headache',
              'abdominal tenderness',
              'patient non compliance',
              'photophobia',
              'night sweat',
              'painful swallowing',
              'poor dentition',
              'transaminitis',
              'non-productive cough',
              'adverse reaction',
              'adverse effect',
              'abdominal bloating'],
             'oral\xa0candidiasis': ['diarrhea',
              'throat sore',
              'decreased body weight',
              'chill',
              'headache',
              'abdominal tenderness',
              'patient non compliance',
              'photophobia',
              'night sweat',
              'painful swallowing',
              'poor dentition',
              'transaminitis',
              'non-productive cough',
              'adverse reaction',
              'adverse effect',
              'abdominal bloating'],
             'neuropathy': ['asthenia',
              'numbness',
              'nausea and vomiting',
              'awakening early',
              'hydropneumothorax',
              'superimposition',
              'fatigability',
              'tenesmus',
              'pain',
              'slowing of urinary stream'],
             'kidney disease': ['shortness of breath',
              'hyperkalemia',
              'pain chest',
              'fever',
              'gravida 0',
              'bleeding of vagina'],
             'fibroid tumor': ['para 2',
              'haemorrhage',
              'abortion',
              'intermenstrual heavy bleeding',
              'muscle hypotonia',
              'hypotonic',
              'previous pregnancies 2',
              'shortness of breath',
              'fever',
              'heartburn',
              'primigravida',
              'abnormally hard consistency',
              'proteinemia'],
             'glaucoma': ['fall',
              'distended abdomen',
              'unsteady gait',
              'paresthesia',
              'hyponatremia',
              'agitation',
              'unconscious state',
              'burning sensation',
              'lesion',
              'mass of body structure'],
             'neoplasm metastasis': ['thicken',
              'tumor cell invasion',
              'metastatic lesion',
              'pain neck',
              'lung nodule',
              'pain',
              'pain abdominal',
              'food intolerance',
              'mass of body structure',
              'atypia'],
             'malignant tumor of colon': ['lesion',
              'prostatism',
              'constipation',
              'general discomfort',
              'diarrhea',
              'pain abdominal',
              'urinary hesitation',
              'dizzy spells',
              'shooting pain',
              'bradycardia',
              'vomiting',
              'systolic ejection murmur',
              'nausea',
              'hyperemesis',
              'polydypsia'],
             'carcinoma colon': ['lesion',
              'prostatism',
              'constipation',
              'general discomfort',
              'diarrhea',
              'pain abdominal',
              'urinary hesitation',
              'dizzy spells',
              'shooting pain',
              'bradycardia',
              'vomiting',
              'systolic ejection murmur',
              'nausea',
              'hyperemesis',
              'polydypsia'],
             'ketoacidosis diabetic': ['polyuria',
              'vomiting',
              'nausea',
              'pain abdominal',
              'milky',
              'feeling strange',
              'gurgle',
              'nervousness',
              'abdominal tenderness',
              'regurgitates after swallowing',
              'vision blurred',
              'urinary hesitation',
              'diarrhea',
              'seizure',
              'aura'],
             'tonic-clonic epilepsy': ['drowsiness',
              'lip smacking',
              'myoclonus',
              'tremor',
              'phonophobia',
              'rolling of eyes',
              'sleepy',
              'hirsutism',
              'moody',
              'muscle twitch',
              'unresponsiveness',
              'headache',
              'ambidexterity',
              'absences finding',
              'spasm',
              'decreased body weight',
              'tumor cell invasion'],
             'tonic-clonic seizures': ['drowsiness',
              'lip smacking',
              'myoclonus',
              'tremor',
              'phonophobia',
              'rolling of eyes',
              'sleepy',
              'hirsutism',
              'moody',
              'muscle twitch',
              'unresponsiveness',
              'headache',
              'ambidexterity',
              'absences finding',
              'spasm',
              'decreased body weight',
              'tumor cell invasion'],
             'malignant\xa0neoplasms': ['pulsus\xa0paradoxus',
              'gravida 10',
              'mass of body structure',
              'lesion',
              'heartburn',
              'night sweat',
              'thicken',
              'chill',
              'decreased translucency',
              'pain abdominal',
              'dullness',
              'food intolerance',
              'distress respiratory',
              'hypotension'],
             'respiratory failure': ['hemiplegia',
              'snore',
              'unresponsiveness',
              'productive cough',
              'dyspnea',
              'tachypnea',
              'hyperkalemia',
              'hypokinesia',
              'sinus rhythm',
              'general unsteadiness',
              'bruit',
              'consciousness clear',
              'shortness of breath',
              'lesion',
              'redness'],
             'melanoma': ['mass of body structure',
              'paraparesis',
              'fever',
              'gravida 0',
              'pain',
              'pruritus',
              'mass in breast',
              'vomiting',
              'diarrhea'],
             'gastroenteritis': ['pain abdominal',
              'breath-holding spell',
              'nausea',
              'decreased body weight',
              'sore to touch',
              'scleral\xa0icterus',
              'fever',
              'myalgia',
              'hyponatremia',
              'retch',
              'mass of body structure',
              'decreased body weight'],
             'malignant neoplasm of lung': ['lesion',
              'cough',
              'lung nodule',
              'shortness of breath',
              'haemoptysis',
              'debilitation',
              'gurgle',
              'ache',
              'rale',
              'night sweat',
              'decreased translucency',
              'asthenia',
              'metastatic lesion',
              'agitation',
              'irritable mood'],
             'carcinoma of lung': ['lesion',
              'cough',
              'lung nodule',
              'shortness of breath',
              'haemoptysis',
              'debilitation',
              'gurgle',
              'ache',
              'rale',
              'night sweat',
              'decreased translucency',
              'asthenia',
              'metastatic lesion',
              'agitation',
              'irritable mood'],
             'manic disorder': ['energy increased',
              'suicidal',
              'hypersomnia',
              'feeling suicidal',
              'blanch',
              'hallucinations auditory',
              'hallucinations visual',
              'elation',
              'verbal auditory hallucinations',
              'feeling hopeless',
              'difficulty',
              'decompensation',
              'verbally abusive behavior',
              'suicidal',
              'feeling suicidal'],
             'personality disorder': ['nightmare',
              'feeling hopeless',
              'transsexual',
              'hallucinations auditory',
              'irritable mood',
              'sleeplessness',
              'agitation',
              'weepiness',
              'mood depressed',
              'scratch marks',
              'nausea and vomiting',
              'extreme exhaustion',
              'side pain',
              'worry',
              'enuresis',
              'homelessness',
              'nervousness',
              'ascites',
              'pruritus'],
             'primary carcinoma of the liver cells': ['mass of body structure',
              'splenomegaly',
              'lesion',
              'paresis',
              'tumor cell invasion',
              'room spinning',
              'haemorrhage',
              'thicken',
              'indifferent mood',
              'cachexia',
              'hypothermia, natural',
              'pain abdominal',
              'hepatomegaly',
              'hematocrit decreased',
              'stupor',
              'decreased body weight',
              'shortness of breath',
              'cough'],
             'emphysema pulmonary': ['behavior showing increased motor activity',
              'scar tissue',
              'dyspnea on exertion',
              'coordination abnormal',
              'myalgia',
              'hypercapnia',
              'clammy skin',
              'has religious belief',
              'room spinning',
              'moan',
              'night sweat',
              'cachexia',
              'symptom aggravating factors',
              'dyspnea',
              'rale',
              'flushing',
              'painful swallowing',
              'arthralgia',
              'choke',
              'tenesmus',
              'constipation'],
             'hemorrhoids': ['haemorrhage',
              'bowel sounds decreased',
              'decreased stool caliber',
              'nausea and vomiting',
              'hunger',
              'diarrhea',
              'dizziness',
              'hyponatremia',
              'clonus',
              'pain',
              'achalasia',
              'burning sensation',
              'guaiac positive',
              'numbness of hand',
              'wheezing',
              'cough'],
             'spasm bronchial': ['shortness of breath',
              'scar tissue',
              'apyrexial',
              'no known drug allergies',
              'pain',
              'productive cough',
              'throat sore',
              'dyspnea',
              'chest tightness',
              'hypoxemia',
              'tachypnea',
              'sensory discomfort',
              'fever',
              'vomiting',
              'rhonchus',
              'hemiplegia',
              'fremitus'],
             'aphasia': ['clonus',
              'egophony',
              'facial paresis',
              'aphagia',
              'muscle twitch',
              'paralyse',
              'low back pain',
              'charleyhorse'],
             'obesity morbid': ['out of breath',
              'sedentary',
              'angina pectoris',
              'cough',
              'unhappy',
              'labored breathing',
              'hypothermia, natural',
              'dyspnea',
              'hematocrit decreased',
              'wheezing',
              'hypoxemia',
              'renal angle tenderness',
              'feels hot/feverish'],
             'pyelonephritis': ['fever',
              'pain',
              'urgency of\xa0micturition',
              'hematuria',
              'vomiting',
              'chill',
              'diarrhea',
              'nausea',
              'pain abdominal',
              'myalgia',
              'fever',
              'chill'],
             'endocarditis': ['pleuritic pain',
              'thicken',
              'myalgia',
              'apyrexial',
              'night sweat',
              'flare',
              'shortness of breath',
              'orthopnea',
              'abscess bacterial',
              'hypotension',
              'cough',
              'metastatic lesion',
              'breath sounds decreased',
              'decreased body weight',
              'decreased body weight',
              'pulsus\xa0paradoxus',
              'hypokinesia'],
             'effusion pericardial': ['pericardial friction rub',
              'dyspnea',
              'shortness of breath',
              'hemodynamically stable',
              'cardiomegaly',
              'hypotension',
              'sputum purulent',
              'facial paresis',
              'pain',
              'oliguria',
              'blackout',
              'intoxication'],
             'pericardial effusion body substance': ['pericardial friction rub',
              'dyspnea',
              'shortness of breath',
              'hemodynamically stable',
              'cardiomegaly',
              'hypotension',
              'sputum purulent',
              'facial paresis',
              'pain',
              'oliguria',
              'blackout',
              'intoxication'],
             'chronic alcoholic intoxication': ['tremor',
              'hallucinations auditory',
              'suicidal',
              'hoard',
              'irritable mood',
              'feeling hopeless',
              'feeling suicidal',
              'neologism',
              'seizure',
              'homelessness',
              'sleeplessness',
              'unconscious state',
              'panic',
              'breath sounds decreased',
              'shortness of breath'],
             'pneumothorax': ['dyspnea',
              'cardiovascular finding',
              'cardiovascular event',
              'haemoptysis',
              'cough',
              'hypercapnia',
              'soft tissue swelling',
              'prostatism',
              'agitation'],
             'delirium': ['unsteady gait',
              'withdraw',
              'hyponatremia',
              'verbally abusive behavior',
              'feeling suicidal',
              'unresponsiveness',
              'worry',
              'drowsiness',
              'sleepy',
              'hallucinations auditory',
              'suicidal',
              'fever',
              'diarrhea'],
             'neutropenia': ['transaminitis',
              'splenomegaly',
              'night sweat',
              'apyrexial',
              'lesion',
              'snuffle',
              'chill',
              'cough',
              'monoclonal',
              'hypocalcemia result',
              'oliguria',
              'rhd positive',
              'distress respiratory'],
             'hyperbilirubinemia': ['cyanosis',
              'tachypnea',
              'para 1',
              'bradycardia',
              'breech presentation',
              'cushingoid facies',
              'cushingoid\xa0habitus',
              'cough',
              'myalgia'],
             'influenza': ['uncoordination',
              'fever',
              'pleuritic pain',
              'snuffle',
              'throat sore',
              'malaise',
              'debilitation',
              'symptom aggravating factors',
              'chill',
              'scleral\xa0icterus',
              'nasal flaring',
              'dysuria',
              'lip smacking',
              'headache',
              'sneeze',
              'snore',
              'green sputum',
              'shortness of breath',
              'distress respiratory',
              'blackout',
              'extreme exhaustion'],
             'dependence': ['intoxication',
              'tremor',
              'agitation',
              'suicidal',
              'homelessness',
              'prostatism',
              'lethargy',
              'seizure',
              'muscle twitch',
              'stuffy nose',
              'feeling hopeless',
              'heavy legs',
              'rale'],
             'thrombus': ['hypokinesia',
              'anorexia',
              'hypertonicity',
              'shortness of breath',
              'hypoalbuminemia',
              'pruritus',
              'sore to touch',
              'hemodynamically stable',
              'facial paresis',
              'vomiting',
              'stool color yellow'],
             'cholecystitis': ['moan',
              'nausea',
              'pain abdominal',
              "Murphy's sign",
              'flatulence',
              'colic abdominal',
              'pain',
              'ascites',
              'diarrhea',
              'qt interval prolonged',
              'cardiovascular finding',
              'cardiovascular event',
              'groggy',
              'sinus rhythm',
              'gasping for breath',
              'constipation',
              'feces in rectum',
              'abnormally hard consistency'],
             'hernia\xa0hiatal': ['pain abdominal',
              'fatigability',
              'prodrome',
              'vomiting',
              'nausea',
              'myalgia',
              'hyponatremia',
              'sore to touch',
              'general discomfort',
              'dyspnea on exertion',
              'asterixis',
              'guaiac positive',
              'numbness of hand',
              'headache',
              'photophobia'],
             'migraine disorders': ['ambidexterity',
              'vomiting',
              'dizziness',
              'numbness',
              'nausea',
              'fever',
              'splenomegaly'],
             'pancytopenia': ['hypoproteinemia',
              'fatigue',
              'haemorrhage',
              'fatigability',
              'cushingoid facies',
              'cushingoid\xa0habitus',
              'stool color yellow',
              'colic abdominal'],
             'cholelithiasis': ['vomiting',
              'nausea',
              'pain abdominal',
              'pain',
              'cushingoid facies',
              'cushingoid\xa0habitus',
              'ascites',
              'thicken',
              'sore to touch',
              'diarrhea',
              'apyrexial',
              'palpitation'],
             'biliary calculus': ['vomiting',
              'nausea',
              'pain abdominal',
              'pain',
              'cushingoid facies',
              'cushingoid\xa0habitus',
              'ascites',
              'thicken',
              'sore to touch',
              'diarrhea',
              'apyrexial',
              'palpitation'],
             'tachycardia sinus': ['left\xa0atrial\xa0hypertrophy',
              'sweat',
              'sweating increased',
              'alcohol binge episode',
              'pressure chest',
              'scar tissue',
              'cardiovascular finding',
              'cardiovascular event',
              'orthostasis',
              'shortness of breath',
              't wave inverted',
              'vomiting',
              'pain abdominal'],
             'ileus': ['abscess bacterial',
              'abdomen acute',
              'air fluid level',
              'catching breath',
              'abdominal tenderness',
              'nausea',
              'sore to touch',
              'flatulence',
              'diarrhea',
              'mass of body structure',
              'apyrexial',
              'constipation',
              'thicken',
              'gravida 0',
              'pain abdominal'],
             'adhesion': ['flatulence',
              'pain',
              'large-for-dates fetus',
              'para 1',
              'vomiting',
              'lung nodule',
              'breech presentation',
              'shortness of breath',
              'decreased body weight',
              'immobile',
              'unsteady gait',
              'hallucinations visual',
              'feeling suicidal'],
             'delusion': ['loose associations',
              'giddy mood',
              'feeling hopeless',
              'agitation',
              'hallucinations auditory',
              'irritable mood',
              'sleeplessness',
              'neologism',
              'homicidal thoughts',
              'disturbed family',
              'worry',
              'decompensation',
              'verbally abusive behavior',
              'catatonia',
              'suicidal',
              'terrify',
              'blackout',
              'weepiness',
              'impaired cognition',
              'irritable mood',
              'agitation'],
             'affect labile': ['extreme exhaustion',
              'sleeplessness',
              'enuresis',
              'patient non compliance',
              'feeling hopeless',
              'hallucinations visual',
              'bedridden',
              'bedridden',
              'prostatism'],
             'decubitus ulcer': ['systolic murmur',
              'frail',
              'fever',
              'fever']})
# Count of Disease Occurence w.r.t each Disease
disease_symptom_count
{'hypertensive disease': 3363.0,
 'diabetes': 1421.0,
 'depression mental': 1337.0,
 'depressive disorder': 1337.0,
 'coronary arteriosclerosis': 1284.0,
 'coronary heart disease': 1284.0,
 'pneumonia': 1029.0,
 'failure heart congestive': 963.0,
 'accident\xa0cerebrovascular': 885.0,
 'asthma': 835.0,
 'myocardial infarction': 759.0,
 'hypercholesterolemia': 685.0,
 'infection': 630.0,
 'infection urinary tract': 597.0,
 'anemia': 544.0,
 'chronic obstructive airway disease': 524.0,
 'dementia': 504.0,
 'insufficiency renal': 445.0,
 'confusion': 408.0,
 'degenerative\xa0polyarthritis': 405.0,
 'hypothyroidism': 398.0,
 'anxiety state': 390.0,
 'malignant neoplasms': 354.0,
 'primary malignant neoplasm': 354.0,
 'acquired\xa0immuno-deficiency syndrome': 350.0,
 'HIV': 350.0,
 'hiv infections': 350.0,
 'cellulitis': 341.0,
 'gastroesophageal reflux disease': 325.0,
 'septicemia': 311.0,
 'systemic infection': 311.0,
 'sepsis (invertebrate)': 311.0,
 'deep vein thrombosis': 310.0,
 'dehydration': 297.0,
 'neoplasm': 297.0,
 'embolism pulmonary': 294.0,
 'epilepsy': 290.0,
 'cardiomyopathy': 283.0,
 'chronic kidney failure': 280.0,
 'carcinoma': 269.0,
 'hepatitis C': 269.0,
 'peripheral vascular disease': 268.0,
 'psychotic disorder': 267.0,
 'hyperlipidemia': 247.0,
 'bipolar disorder': 241.0,
 'obesity': 228.0,
 'ischemia': 226.0,
 'cirrhosis': 218.0,
 'exanthema': 208.0,
 'benign prostatic hypertrophy': 192.0,
 'kidney failure acute': 186.0,
 'mitral valve insufficiency': 186.0,
 'arthritis': 179.0,
 'bronchitis': 172.0,
 'hemiparesis': 171.0,
 'osteoporosis': 169.0,
 'transient ischemic attack': 168.0,
 'adenocarcinoma': 166.0,
 'paranoia': 165.0,
 'pancreatitis': 165.0,
 'incontinence': 165.0,
 'paroxysmal\xa0dyspnea': 165.0,
 'hernia': 164.0,
 'malignant neoplasm of prostate': 163.0,
 'carcinoma prostate': 163.0,
 'edema pulmonary': 161.0,
 'lymphatic diseases': 160.0,
 'stenosis aortic valve': 158.0,
 'malignant neoplasm of breast': 152.0,
 'carcinoma breast': 152.0,
 'schizophrenia': 147.0,
 'diverticulitis': 145.0,
 'overload fluid': 144.0,
 'ulcer peptic': 143.0,
 'osteomyelitis': 142.0,
 'gastritis': 140.0,
 'bacteremia': 142.0,
 'failure kidney': 140.0,
 'sickle cell anemia': 140.0,
 'failure heart': 138.0,
 'upper respiratory infection': 135.0,
 'hepatitis': 133.0,
 'hypertension pulmonary': 128.0,
 'deglutition disorder': 126.0,
 'gout': 124.0,
 'thrombocytopaenia': 123.0,
 'hypoglycemia': 122.0,
 'pneumonia aspiration': 119.0,
 'colitis': 114.0,
 'diverticulosis': 114.0,
 'suicide attempt': 114.0,
 'Pneumocystis\xa0carinii\xa0pneumonia': 113.0,
 'hepatitis B': 111.0,
 'parkinson disease': 108.0,
 'lymphoma': 105.0,
 'hyperglycemia': 104.0,
 'encephalopathy': 103.0,
 'tricuspid valve insufficiency': 101.0,
 "Alzheimer's disease": 101.0,
 'candidiasis': 99.0,
 'oral\xa0candidiasis': 99.0,
 'neuropathy': 99.0,
 'kidney disease': 96.0,
 'fibroid tumor': 96.0,
 'glaucoma': 95.0,
 'neoplasm metastasis': 94.0,
 'malignant tumor of colon': 94.0,
 'carcinoma colon': 94.0,
 'ketoacidosis diabetic': 93.0,
 'tonic-clonic epilepsy': 92.0,
 'tonic-clonic seizures': 92.0,
 'malignant\xa0neoplasms': 90.0,
 'respiratory failure': 90.0,
 'melanoma': 87.0,
 'gastroenteritis': 87.0,
 'malignant neoplasm of lung': 86.0,
 'carcinoma of lung': 86.0,
 'manic disorder': 85.0,
 'personality disorder': 84.0,
 'primary carcinoma of the liver cells': 82.0,
 'emphysema pulmonary': 80.0,
 'hemorrhoids': 80.0,
 'spasm bronchial': 76.0,
 'aphasia': 76.0,
 'obesity morbid': 76.0,
 'pyelonephritis': 74.0,
 'endocarditis': 71.0,
 'effusion pericardial': 71.0,
 'pericardial effusion body substance': 71.0,
 'chronic alcoholic intoxication': 70.0,
 'pneumothorax': 68.0,
 'delirium': 68.0,
 'neutropenia': 68.0,
 'hyperbilirubinemia': 68.0,
 'influenza': 68.0,
 'dependence': 67.0,
 'thrombus': 67.0,
 'cholecystitis': 66.0,
 'hernia\xa0hiatal': 61.0,
 'migraine disorders': 61.0,
 'pancytopenia': 61.0,
 'cholelithiasis': 61.0,
 'biliary calculus': 61.0,
 'tachycardia sinus': 56.0,
 'ileus': 56.0,
 'adhesion': 57.0,
 'delusion': 56.0,
 'affect labile': 45.0,
 'decubitus ulcer': 42.0}
# Save cleaned data as CSV
f = open('./dataset/cleaned_data.csv', 'w')

with f:
    writer = csv.writer(f)
    for key, val in disease_symptom_dict.items():
        for i in range(len(val)):
            writer.writerow([key, val[i], disease_symptom_count[key]])
# Read Cleaned Data as DF
df = pd.read_csv('./dataset/cleaned_data.csv')
df.columns = ['disease', 'symptom', 'occurence_count']
df.head()
disease	symptom	occurence_count
0	hypertensive disease	shortness of breath	3363.0
1	hypertensive disease	dizziness	3363.0
2	hypertensive disease	asthenia	3363.0
3	hypertensive disease	fall	3363.0
4	hypertensive disease	syncope	3363.0
# Remove any rows with empty values
df.replace(float('nan'), np.nan, inplace=True)
df.dropna(inplace=True)
from sklearn import preprocessing
n_unique = len(df['symptom'].unique())
n_unique
404
df.dtypes
disease             object
symptom             object
occurence_count    float64
dtype: object
# Encode the Labels
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

label_encoder = LabelEncoder()
integer_encoded = label_encoder.fit_transform(df['symptom'])
print(integer_encoded)
[328  87  28 ... 130 122 122]
# One Hot Encode the Labels
onehot_encoder = OneHotEncoder(sparse=False)
integer_encoded = integer_encoded.reshape(len(integer_encoded), 1)
onehot_encoded = onehot_encoder.fit_transform(integer_encoded)
print(onehot_encoded)
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
onehot_encoded[0]
array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
len(onehot_encoded[0])
404
cols = np.asarray(df['symptom'].unique())
cols
array(['shortness of breath', 'dizziness', 'asthenia', 'fall', 'syncope',
       'vertigo', 'sweat', 'sweating increased', 'palpitation', 'nausea',
       'angina pectoris', 'pressure chest', 'polyuria', 'polydypsia',
       'pain chest', 'orthopnea', 'rale', 'unresponsiveness',
       'mental status changes', 'vomiting', 'labored breathing',
       'feeling suicidal', 'suicidal', 'hallucinations auditory',
       'feeling hopeless', 'weepiness', 'sleeplessness',
       'motor retardation', 'irritable mood', 'blackout',
       'mood depressed', 'hallucinations visual', 'worry', 'agitation',
       'tremor', 'intoxication', 'verbal auditory hallucinations',
       'energy increased', 'difficulty', 'nightmare',
       'unable to concentrate', 'homelessness', 'hypokinesia',
       'dyspnea on exertion', 'chest tightness', 'cough', 'fever',
       'decreased translucency', 'productive cough', 'pleuritic pain',
       'yellow sputum', 'breath sounds decreased', 'chill', 'rhonchus',
       'green sputum', 'non-productive cough', 'wheezing', 'haemoptysis',
       'distress respiratory', 'tachypnea', 'malaise', 'night sweat',
       'jugular venous distention', 'dyspnea', 'dysarthria',
       'speech slurred', 'facial paresis', 'hemiplegia', 'seizure',
       'numbness', 'symptom aggravating factors', 'st segment elevation',
       'st segment depression', 't wave inverted', 'presence of q wave',
       'chest discomfort', 'bradycardia', 'pain', 'nonsmoker', 'erythema',
       'hepatosplenomegaly', 'pruritus', 'diarrhea', 'abscess bacterial',
       'swelling', 'apyrexial', 'dysuria', 'hematuria',
       'renal angle tenderness', 'lethargy', 'hyponatremia',
       'hemodynamically stable', 'difficulty passing urine',
       'consciousness clear', 'guaiac positive', 'monoclonal',
       'ecchymosis', 'tumor cell invasion', 'haemorrhage', 'pallor',
       'fatigue', 'heme positive', 'pain back', 'orthostasis',
       'arthralgia', 'transaminitis', 'sputum purulent', 'hypoxemia',
       'hypercapnia', 'patient non compliance', 'unconscious state',
       'bedridden', 'abdominal tenderness', 'unsteady gait',
       'hyperkalemia', 'urgency of\xa0micturition', 'ascites',
       'hypotension', 'enuresis', 'asterixis', 'muscle twitch', 'sleepy',
       'headache', 'lightheadedness', 'food intolerance',
       'numbness of hand', 'general discomfort', 'drowsiness',
       'stiffness', 'prostatism', 'weight gain', 'tired',
       'mass of body structure', 'has religious belief', 'nervousness',
       'formication', 'hot flush', 'lesion', 'cushingoid facies',
       'cushingoid\xa0habitus', 'emphysematous change',
       'decreased body weight', 'hoarseness', 'thicken',
       'spontaneous rupture of membranes', 'muscle hypotonia',
       'hypotonic', 'redness', 'hypesthesia', 'hyperacusis',
       'scratch marks', 'sore to touch', 'burning sensation',
       'satiety early', 'throbbing sensation quality',
       'sensory discomfort', 'constipation', 'pain abdominal',
       'heartburn', 'breech presentation', 'cyanosis',
       'pain in lower limb', 'cardiomegaly', 'clonus', 'unwell',
       'anorexia', 'history of - blackout', 'anosmia',
       'metastatic lesion', 'hemianopsia homonymous',
       'hematocrit decreased', 'neck stiffness', 'cicatrisation',
       'hypometabolism', 'aura', 'myoclonus', 'gurgle',
       'wheelchair bound', 'left\xa0atrial\xa0hypertrophy', 'oliguria',
       'catatonia', 'unhappy', 'paresthesia', 'gravida 0', 'lung nodule',
       'distended abdomen', 'ache', 'macerated skin', 'heavy feeling',
       'rest pain', 'sinus rhythm', 'withdraw', 'behavior hyperactive',
       'terrify', 'photopsia', 'giddy mood', 'disturbed family',
       'hypersomnia', 'hyperhidrosis disorder', 'mydriasis',
       'extrapyramidal sign', 'loose associations', 'exhaustion', 'snore',
       'r wave feature', 'overweight', 'systolic murmur', 'asymptomatic',
       'splenomegaly', 'bleeding of vagina', 'macule', 'photophobia',
       'painful swallowing', 'cachexia', 'hypocalcemia result',
       'hypothermia, natural', 'atypia', 'general unsteadiness',
       'throat sore', 'snuffle', 'hacking cough', 'stridor', 'paresis',
       'aphagia', 'focal seizures', 'abnormal sensation', 'stupor',
       'fremitus', "Stahli's line", 'stinging sensation', 'paralyse',
       'hirsutism', 'sniffle', 'bradykinesia', 'out of breath',
       'urge incontinence', 'vision blurred', 'room spinning',
       'rambling speech', 'clumsiness', 'decreased stool caliber',
       'hematochezia', 'egophony', 'scar tissue', 'neologism',
       'decompensation', 'stool color yellow',
       'rigor - temperature-associated observation', 'paraparesis',
       'moody', 'fear of falling', 'spasm', 'hyperventilation',
       'excruciating pain', 'gag', 'posturing', 'pulse absent',
       'dysesthesia', 'polymyalgia', 'passed stones',
       'qt interval prolonged', 'ataxia', "Heberden's node",
       'hepatomegaly', 'sciatica', 'frothy sputum', 'mass in breast',
       'retropulsion', 'estrogen use', 'hypersomnolence', 'underweight',
       'dullness', 'red blotches', 'colic abdominal', 'hypokalemia',
       'hunger', 'prostate tender', 'pain foot', 'urinary hesitation',
       'disequilibrium', 'flushing', 'indifferent mood', 'urinoma',
       'hypoalbuminemia', 'pustule', 'slowing of urinary stream',
       'extreme exhaustion', 'no status change', 'breakthrough pain',
       'pansystolic murmur', 'systolic ejection murmur', 'stuffy nose',
       'barking cough', 'rapid shallow breathing', 'noisy respiration',
       'nasal discharge present', 'frail', 'cystic lesion',
       'projectile vomiting', 'heavy legs', 'titubation',
       'dysdiadochokinesia', 'achalasia', 'side pain', 'monocytosis',
       'posterior\xa0rhinorrhea', 'incoherent', 'lameness',
       'claudication', 'clammy skin', 'mediastinal shift',
       'nausea and vomiting', 'awakening early', 'tenesmus', 'fecaluria',
       'pneumatouria', 'todd paralysis', 'alcoholic withdrawal symptoms',
       'myalgia', 'dyspareunia', 'poor dentition', 'floppy',
       'inappropriate affect', 'poor feeding', 'moan', 'welt', 'tinnitus',
       'hydropneumothorax', 'superimposition', 'feeling strange',
       'uncoordination', 'absences finding', 'tonic seizures',
       'debilitation', 'impaired cognition', 'drool', 'pin-point pupils',
       'tremor resting', 'groggy', 'adverse reaction', 'adverse effect',
       'abdominal bloating', 'fatigability', 'para 2', 'abortion',
       'intermenstrual heavy bleeding', 'previous pregnancies 2',
       'primigravida', 'abnormally hard consistency', 'proteinemia',
       'pain neck', 'dizzy spells', 'shooting pain', 'hyperemesis',
       'milky', 'regurgitates after swallowing', 'lip smacking',
       'phonophobia', 'rolling of eyes', 'ambidexterity',
       'pulsus\xa0paradoxus', 'gravida 10', 'bruit',
       'breath-holding spell', 'scleral\xa0icterus', 'retch', 'blanch',
       'elation', 'verbally abusive behavior', 'transsexual',
       'behavior showing increased motor activity',
       'coordination abnormal', 'choke', 'bowel sounds decreased',
       'no known drug allergies', 'low back pain', 'charleyhorse',
       'sedentary', 'feels hot/feverish', 'flare',
       'pericardial friction rub', 'hoard', 'panic',
       'cardiovascular finding', 'cardiovascular event',
       'soft tissue swelling', 'rhd positive', 'para 1', 'nasal flaring',
       'sneeze', 'hypertonicity', "Murphy's sign", 'flatulence',
       'gasping for breath', 'feces in rectum', 'prodrome',
       'hypoproteinemia', 'alcohol binge episode', 'abdomen acute',
       'air fluid level', 'catching breath', 'large-for-dates fetus',
       'immobile', 'homicidal thoughts'], dtype=object)
# Create a new dataframe to save OHE labels
df_ohe = pd.DataFrame(columns = cols)
df_ohe.head()
shortness of breath	dizziness	asthenia	fall	syncope	vertigo	sweat	sweating increased	palpitation	nausea	...	feces in rectum	prodrome	hypoproteinemia	alcohol binge episode	abdomen acute	air fluid level	catching breath	large-for-dates fetus	immobile	homicidal thoughts
0 rows × 404 columns

for i in range(len(onehot_encoded)):
    df_ohe.loc[i] = onehot_encoded[i]
df_ohe.head()
shortness of breath	dizziness	asthenia	fall	syncope	vertigo	sweat	sweating increased	palpitation	nausea	...	feces in rectum	prodrome	hypoproteinemia	alcohol binge episode	abdomen acute	air fluid level	catching breath	large-for-dates fetus	immobile	homicidal thoughts
0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	...	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0
1	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	...	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0
2	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	...	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0
3	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	...	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0
4	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	...	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0
5 rows × 404 columns

len(df_ohe)
2127
# Disease Dataframe
df_disease = df['disease']
df_disease.head()
0    hypertensive disease
1    hypertensive disease
2    hypertensive disease
3    hypertensive disease
4    hypertensive disease
Name: disease, dtype: object
# Concatenate OHE Labels with the Disease Column
df_concat = pd.concat([df_disease,df_ohe], axis=1)
df_concat.head()
disease	shortness of breath	dizziness	asthenia	fall	syncope	vertigo	sweat	sweating increased	palpitation	...	feces in rectum	prodrome	hypoproteinemia	alcohol binge episode	abdomen acute	air fluid level	catching breath	large-for-dates fetus	immobile	homicidal thoughts
0	hypertensive disease	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	...	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0
1	hypertensive disease	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	...	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0
2	hypertensive disease	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	...	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0
3	hypertensive disease	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	...	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0
4	hypertensive disease	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	...	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0
5 rows × 405 columns

df_concat.drop_duplicates(keep='first',inplace=True)
df_concat.head()
disease	shortness of breath	dizziness	asthenia	fall	syncope	vertigo	sweat	sweating increased	palpitation	...	feces in rectum	prodrome	hypoproteinemia	alcohol binge episode	abdomen acute	air fluid level	catching breath	large-for-dates fetus	immobile	homicidal thoughts
0	hypertensive disease	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	...	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0
1	hypertensive disease	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	...	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0
2	hypertensive disease	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	...	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0
3	hypertensive disease	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	...	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0
4	hypertensive disease	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	...	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0
5 rows × 405 columns

len(df_concat)
2098
cols = df_concat.columns
cols
Index(['disease', 'shortness of breath', 'dizziness', 'asthenia', 'fall',
       'syncope', 'vertigo', 'sweat', 'sweating increased', 'palpitation',
       ...
       'feces in rectum', 'prodrome', 'hypoproteinemia',
       'alcohol binge episode', 'abdomen acute', 'air fluid level',
       'catching breath', 'large-for-dates fetus', 'immobile',
       'homicidal thoughts'],
      dtype='object', length=405)
cols = cols[1:]
# Since, every disease has multiple symptoms, combine all symptoms per disease per row
df_concat = df_concat.groupby('disease').sum()
df_concat = df_concat.reset_index()
df_concat[:5]
disease	shortness of breath	dizziness	asthenia	fall	syncope	vertigo	sweat	sweating increased	palpitation	...	feces in rectum	prodrome	hypoproteinemia	alcohol binge episode	abdomen acute	air fluid level	catching breath	large-for-dates fetus	immobile	homicidal thoughts
0	Alzheimer's disease	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	...	0.0	0.0	0.0	0.0	0.0	1.0	0.0	0.0	0.0	0.0
1	HIV	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	...	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0
2	Pneumocystis carinii pneumonia	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	...	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	1.0
3	accident cerebrovascular	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	...	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0
4	acquired immuno-deficiency syndrome	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	...	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0	0.0
5 rows × 405 columns

len(df_concat)
149
df_concat.to_csv("./dataset/training_dataset.csv", index=False)
# One Hot Encoded Features
X = df_concat[cols]

# Labels
y = df_concat['disease']
Model Training
from sklearn.model_selection import train_test_split
from sklearn.naive_bayes import MultinomialNB
from sklearn import tree
from sklearn.tree import DecisionTreeClassifier, export_graphviz
# Train Test Split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=101)
len(X_train), len(y_train)
(119, 119)
len(X_test), len(y_test)
(30, 30)
dt = DecisionTreeClassifier()
clf_dt=dt.fit(X, y)
clf_dt.score(X, y)
0.9731543624161074
export_graphviz(dt, 
                out_file='./tree.dot', 
                feature_names=cols)
!pip install graphviz
Requirement already satisfied: graphviz in /Users/anujdutt/miniconda3/envs/DL/lib/python3.8/site-packages (0.16)
from graphviz import Source
from sklearn import tree

graph = Source(export_graphviz(dt, 
                out_file=None, 
                feature_names=cols))

png_bytes = graph.pipe(format='png')

with open('tree.png','wb') as f:
    f.write(png_bytes)
from IPython.display import Image
Image(png_bytes)

disease_pred = clf_dt.predict(X)
disease_real = y.values
for i in range(0, len(disease_real)):
    if disease_pred[i]!=disease_real[i]:
        print ('Pred: {0}\nActual: {1}\n'.format(disease_pred[i], disease_real[i]))
Pred: coronary arteriosclerosis
Actual: coronary heart disease

Pred: depression mental
Actual: depressive disorder

Pred: malignant neoplasms
Actual: primary malignant neoplasm

Pred: septicemia
Actual: systemic infection
